# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #d8d8d8
background              #0a0a0a
selection_foreground    #ffffff
selection_background    #2a2a2a

# Cursor colors
cursor                  #a11010
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #a11010

# Kitty window border colors
active_border_color     #a11010
inactive_border_color   #a11010
bell_border_color       #a11010

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #a11010
inactive_tab_foreground #888888
inactive_tab_background #1a1a1a
tab_bar_background      #0a0a0a

# Colors for marks (marked text in the terminal)
mark1_foreground #ffffff
mark1_background #a11010
mark2_foreground #ffffff
mark2_background #cc2233
mark3_foreground #ffffff
mark3_background #991b2f

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
